# Generated by Django 5.0.1 on 2025-02-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_userfeedbackmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberSecurityPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_srv_rate', models.FloatField()),
                ('dst_host_srv_diff_host_rate', models.FloatField()),
                ('dst_host_same_src_port_rate', models.FloatField()),
                ('srv_count', models.FloatField()),
                ('protocol_type', models.CharField(max_length=10)),
                ('dst_host_count', models.FloatField()),
                ('logged_in', models.CharField(max_length=10)),
                ('dst_bytes', models.FloatField()),
                ('count', models.FloatField()),
                ('prediction_result', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
